# SPDX-FileCopyrightText: 2015 Naoyuki Kanezawa <naoyuki.kanezawa@gmail.com>
#
# SPDX-License-Identifier: MIT

ui: mocha-bdd
server: ./test/support/server.js
tunnel:
  type: ngrok
  authtoken: XP5uKk4Sm6C5XfdTZozb
  proto: tcp
